//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim_details
    {
        public int claim_num { get; set; }
        public int policy_num { get; set; }
        public string policy_start_date { get; set; }
        public string policy_end_date { get; set; }
        public string cus_name { get; set; }
        public string place_of_accident { get; set; }
        public string date_of_accident { get; set; }
        public int insured_amount { get; set; }
        public int claimable_amount { get; set; }
    }
}
