//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class comp_exp
    {
        public string comp_expenses { get; set; }
        public string type_of_expenses { get; set; }
        public int amount_of_exp { get; set; }
    }
}
