//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class cus_bill_info
    {
        public int cus_id { get; set; }
        public string cus_name { get; set; }
        public int policy_num { get; set; }
        public string cus_add_prove { get; set; }
        public int cus_pho_num { get; set; }
        public int bill_no { get; set; }
        public string veh_name { get; set; }
        public string veh_model { get; set; }
        public int veh_rate { get; set; }
        public string veh_body_num { get; set; }
        public string veh_eng_num { get; set; }
        public string date { get; set; }
        public int amount { get; set; }
    }
}
