//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int cus_Id { get; set; }
        public string cus_Name { get; set; }
        public string cus_Add { get; set; }
        public string cus_ph_num { get; set; }
        public string policy_num { get; set; }
        public string policy_date { get; set; }
        public string policy_duration { get; set; }
        public string veh_num { get; set; }
        public string veh_name { get; set; }
        public string veh_model { get; set; }
        public string veh_version { get; set; }
        public string veh_rate { get; set; }
        public string veh_warranty { get; set; }
        public string veh_boby_num { get; set; }
        public string veh_engine_num { get; set; }
        public string cus_add_prove { get; set; }
    }
}
