//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class estimate
    {
        public int cus_id { get; set; }
        public int Estimate_num { get; set; }
        public string cus_name { get; set; }
        public int cus_phone_num { get; set; }
        public string veh_name { get; set; }
        public string veh_model { get; set; }
        public int veh_rate { get; set; }
        public string veh_warrranty { get; set; }
        public string veh_policy_type { get; set; }
    }
}
