//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<claim_details> claim_details { get; set; }
        public virtual DbSet<cus_bill_info> cus_bill_info { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<estimate> estimates { get; set; }
        public virtual DbSet<signup> signups { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Vehicle_info> Vehicle_info { get; set; }
        public virtual DbSet<comp_exp> comp_exp { get; set; }
    }
}
