//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class signup
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string user_name { get; set; }
        public string Email { get; set; }
        public int age { get; set; }
    }
}
