//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_info
    {
        public int Id { get; set; }
        public string veh_Name { get; set; }
        public string veh_owner_name { get; set; }
        public string veh_model { get; set; }
        public string veh_version { get; set; }
        public int veh_rate { get; set; }
        public string veh_body_num { get; set; }
        public string veh_engine_num { get; set; }
        public int veh_num { get; set; }
    }
}
